import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NewsletterSignup from "@/components/Newsletter";
import Footer from "@/components/Footer";
import { AlertProvider } from "@/context/AlertContext";
import { LoginContextProvider } from "@/context/LoginContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AlertProvider> 
          <LoginContextProvider>
            <Navbar />
            <div className="pt-20">
              {children}
            </div>
            <hr/>
            <NewsletterSignup />
            <Footer />
          </LoginContextProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
